// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701140244_AddIncomeFeature")]
    partial class AddIncomeFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "🍔",
                            IsIncome = false,
                            Name = "Ăn uống"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "☕",
                            IsIncome = false,
                            Name = "Cafe"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "💊",
                            IsIncome = false,
                            Name = "Sức khỏe"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "🚗",
                            IsIncome = false,
                            Name = "Di chuyển"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "🛒",
                            IsIncome = false,
                            Name = "Mua sắm"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "📦",
                            IsIncome = false,
                            Name = "Khác"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "💡",
                            IsIncome = false,
                            Name = "Điện nước"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "📚",
                            IsIncome = false,
                            Name = "Giáo dục"
                        },
                        new
                        {
                            Id = 9,
                            Icon = "🎮",
                            IsIncome = false,
                            Name = "Giải trí"
                        },
                        new
                        {
                            Id = 10,
                            Icon = "🏠",
                            IsIncome = false,
                            Name = "Thuê nhà"
                        },
                        new
                        {
                            Id = 11,
                            Icon = "✈️",
                            IsIncome = false,
                            Name = "Du lịch"
                        },
                        new
                        {
                            Id = 12,
                            Icon = "⚽",
                            IsIncome = false,
                            Name = "Thể thao"
                        },
                        new
                        {
                            Id = 13,
                            Icon = "💰",
                            IsIncome = true,
                            Name = "Tiền lương"
                        },
                        new
                        {
                            Id = 14,
                            Icon = "🎁",
                            IsIncome = true,
                            Name = "Thưởng"
                        },
                        new
                        {
                            Id = 15,
                            Icon = "📈",
                            IsIncome = true,
                            Name = "Đầu tư"
                        },
                        new
                        {
                            Id = 16,
                            Icon = "🏦",
                            IsIncome = true,
                            Name = "Lãi tiết kiệm"
                        },
                        new
                        {
                            Id = 17,
                            Icon = "💵",
                            IsIncome = true,
                            Name = "Thu nhập khác"
                        });
                });

            modelBuilder.Entity("Backend.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIncome")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Backend.Models.Transaction", b =>
                {
                    b.HasOne("Backend.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
